select TENDEAN as Tên_đề_án, ceiling (cast (sum(THOIGIAN) as decimal(5,2))) as 'Tổng số giờ làm việc' FROM CONGVIEC
inner join DEAN on CONGVIEC.MADA=DEAN. MADA
inner join PHANCONG on CONGVIEC.MADA=PHANCONG. MADA
group by TENDEAN

select TENDEAN as Tên_đề_án, floor (cast (sum(THOIGIAN) as decimal(5,2))) as 'Tổng số giờ làm việc' FROM CONGVIEC
inner join DEAN on CONGVIEC.MADA=DEAN. MADA
inner join PHANCONG on CONGVIEC.MADA=PHANCONG. MADA
group by TENDEAN

SELECT HONV+' '+TENLOT+' '+TENNV as Họ_và_tên, LUONG FROM NHANVIEN 
WHERE LUONG >(SELECT ROUND(avg(LUONG), 2) 
FROM NHANVIEN WHERE PHG= (SELECT MAPHG FROM PHONGBAN WHERE TENPHG=N'Nghiên cứu'))

SELECT UPPER(HONV+' '+TENLOT+' '+TENNV) as Họ_và_tên, LUONG FROM NHANVIEN
WHERE LUONG >(SELECT ROUND(avg(LUONG), 2) 
FROM NHANVIEN WHERE PHG= (SELECT MAPHG FROM PHONGBAN WHERE TENPHG=N'Nghiên cứu'))

SELECT TENNV as Tên_nhân_viên
FROM NHANVIEN
WHERE YEAR(NGSINH) between 1960 and 1965

SELECT YEAR(GETDATE())-YEAR(NGSINH) as 'Tuổi' FROM NHANVIEN